export const DRUG_DATABASE: string[] = [
  'Abacavir',
  'Abacavir with dolutegravir and lamivudine',
  'Abacavir with lamivudine',
  'Abacavir with lamivudine and zidovudine',
  'Abaloparatide',
  'Abatacept',
  'Abemaciclib',
  'Abiraterone acetate',
  'Abrocitinib',
  'Acalabrutinib',
  'Acamprosate calcium',
  'Acarbose',
  'Acebutolol',
  'Aceclofenac',
  'Acenocoumarol',
  'Acetazolamide',
  'Acetylcholine chloride',
  'Acetylcysteine',
  'Aciclovir',
  'Acipimox',
  'Acitretin',
  'Aclidinium bromide',
  'Aclidinium bromide with formoterol',
  'Acrivastine',
  'Activated charcoal',
  'Adalimumab',
  'Adapalene',
  'Adapalene with benzoyl peroxide',
  'Adefovir dipivoxil',
  'Adenosine',
  'Adrenaline with articaine hydrochloride',
  'Adrenaline/epinephrine',
  'Afatinib',
  'Aflibercept',
  'Agalsidase alfa',
  'Agalsidase beta',
  'Agomelatine',
  'Albendazole',
  'Albumin solution',
  'Alclometasone dipropionate',
  'Alcohol',
  'Aldesleukin',
  'Alectinib',
  'Alemtuzumab',
  'Alendronic acid',
  'Alendronic acid with colecalciferol',
  'Alfacalcidol',
  'Alfentanil',
  'Alfuzosin hydrochloride',
  'Alginic acid',
  'Alglucosidase alfa',
  'Alimemazine tartrate',
  'Alirocumab',
  'Aliskiren',
  'Alitretinoin',
  'Allopurinol',
  'Almond oil',
  'Almotriptan',
  'Alogliptin',
  'Alogliptin with metformin',
  'Alpelisib',
  'Alpha tocopherol',
  'Alpha tocopheryl acetate',
  'Alprazolam',
  'Alprostadil',
  'Alteplase',
  'Aluminium acetate',
  'Aluminium chloride hexahydrate',
  'Alverine citrate',
  'Alverine with simeticone',
  'Amantadine hydrochloride',
  'Ambrisentan',
  'Amifampridine',
  'Amikacin',
  'Amiloride hydrochloride',
  'Amiloride with bumetanide',
  'Aminophylline',
  'Aminosalicylic acid',
  'Amiodarone hydrochloride',
  'Amisulpride',
  'Amitriptyline hydrochloride',
  'Amivantamab',
  'Amlodipine',
  'Amlodipine with valsartan',
  'Amorolfine',
  'Amoxicillin',
  'Amphotericin B',
  'Ampicillin',
  'Amsacrine',
  'Anagrelide',
  'Anakinra',
  'Anastrozole',
  'Andexanet alfa',
  'Anethol with borneol, camphene, cineole, fenchone and pinene',
  'Angiotensin II',
  'Anidulafungin',
  'Antazoline with xylometazoline',
  'Anthrax vaccine',
  'Anti-D (Rh0) immunoglobulin',
  'Antithymocyte immunoglobulin (rabbit)',
  'Apalutamide',
  'Apixaban',
  'Apomorphine hydrochloride',
  'Apraclonidine',
  'Apremilast',
  'Aprepitant',
  'Arachis oil',
  'Argatroban monohydrate',
  'Aripiprazole',
  'Arsenic trioxide',
  'Artemether with lumefantrine',
  'Artesunate',
  'Asciminib',
  'Ascorbic acid',
  'Asenapine',
  'Asfotase alfa',
  'Asparaginase',
  'Aspirin',
  'Aspirin with codeine',
  'Aspirin with metoclopramide',
  'Ataluren',
  'Atazanavir',
  'Atazanavir with cobicistat',
  'Atenolol',
  'Atezolizumab',
  'Atogepant',
  'Atomoxetine',
  'Atorvastatin',
  'Atosiban',
  'Atovaquone',
  'Atovaquone with proguanil hydrochloride',
  'Atracurium besilate',
  'Atropine sulfate',
  'Avacopan',
  'Avalglucosidase alfa',
  'Avanafil',
  'Avapritinib',
  'Avatrombopag',
  'Avelumab',
  'Aviptadil with phentolamine mesilate',
  'Axitinib',
  'Azacitidine',
  'Azathioprine',
  'Azelaic acid',
  'Azelastine hydrochloride',
  'Azilsartan medoxomil',
  'Azithromycin',
  'Aztreonam',
  'Aztreonam with avibactam',
  'Bacillus Calmette-Guérin',
  'Bacillus Calmette-Guérin vaccine',
  'Baclofen',
  'Baloxavir marboxil',
  'Balsalazide sodium',
  'Baricitinib',
  'Barrier creams and ointments',
  'Basiliximab',
  'Beclometasone dipropionate',
  'Beclometasone with formoterol',
  'Beclometasone with formoterol and glycopyrronium',
  'Bedaquiline',
  'Bee venom extract',
  'Belatacept',
  'Belimumab',
  'Belumosudil',
  'Belzutifan',
  'Bemiparin sodium',
  'Bempedoic acid',
  'Bempedoic acid with ezetimibe',
  'Bendamustine hydrochloride',
  'Bendroflumethiazide',
  'Benperidol',
  'Benralizumab',
  'Benzalkonium chloride',
  'Benzathine benzylpenicillin',
  'Benzoic acid with salicylic acid',
  'Benzoyl peroxide',
  'Benzoyl peroxide with clindamycin',
  'Benzydamine hydrochloride',
  'Benzyl benzoate',
  'Benzyl benzoate with bismuth oxide, bismuth subgallate, hydrocortisone acetate, peru balsam and zinc oxide',
  'Benzylpenicillin sodium',
  'Berotralstat',
  'Betahistine dihydrochloride',
  'Betaine',
  'Betamethasone',
  'Betamethasone with clioquinol',
  'Betamethasone with clotrimazole',
  'Betamethasone with fusidic acid',
  'Betamethasone with neomycin',
  'Betamethasone with salicylic acid',
  'Betaxolol',
  'Bethanechol chloride',
  'Bevacizumab',
  'Bexarotene',
  'Bezafibrate',
  'Bezlotoxumab',
  'Bicalutamide',
  'Bictegravir with emtricitabine and tenofovir alafenamide',
  'Bilastine',
  'Bimatoprost',
  'Bimatoprost with timolol',
  'Bimekizumab',
  'Binimetinib',
  'Biphasic insulin aspart',
  'Biphasic insulin lispro',
  'Biphasic isophane insulin',
  'Birch bark extract',
  'Bisacodyl',
  'Bismuth potassium with metronidazole and tetracycline hydrochloride',
  'Bismuth subsalicylate',
  'Bisoprolol fumarate',
  'Bivalirudin',
  'Bleomycin',
  'Blinatumomab',
  'Borneol with camphene, cineole, menthol, menthone and pinene',
  'Bortezomib',
  'Bosentan',
  'Bosutinib',
  'Botulinum toxin type A',
  'Botulism antitoxin',
  'Brentuximab vedotin',
  'Brigatinib',
  'Brimonidine tartrate',
  'Brimonidine with timolol',
  'Brinzolamide',
  'Brinzolamide with brimonidine',
  'Brinzolamide with timolol',
  'Brivaracetam',
  'Brodalumab',
  'Brolucizumab',
  'Bromfenac',
  'Bromocriptine',
  'Budesonide',
  'Budesonide with formoterol',
  'Bulevirtide',
  'Bumetanide',
  'Bupivacaine hydrochloride',
  'Bupivacaine with adrenaline',
  'Bupivacaine with fentanyl',
  'Buprenorphine',
  'Buprenorphine with naloxone',
  'Bupropion hydrochloride',
  'Burosumab',
  'Buserelin',
  'Buspirone hydrochloride',
  'Busulfan',
  'C1-esterase inhibitor',
  'Cabazitaxel',
  'Cabergoline',
  'Cabotegravir',
  'Cabozantinib',
  'Calamine with zinc oxide',
  'Calcifediol monohydrate',
  'Calcipotriol',
  'Calcipotriol with betamethasone',
  'Calcitonin (salmon)',
  'Calcitriol',
  'Calcium acetate',
  'Calcium acetate with magnesium carbonate',
  'Calcium carbonate',
  'Calcium carbonate with calcium lactate gluconate',
  'Calcium chloride',
  'Calcium gluconate',
  'Calcium lactate',
  'Calcium phosphate',
  'Calcium polystyrene sulfonate',
  'Camellia sinensis',
  'Canagliflozin',
  'Canagliflozin with metformin',
  'Canakinumab',
  'Candesartan cilexetil',
  'Cangrelor',
  'Cannabidiol',
  'Cannabis extract',
  'Capecitabine',
  'Capivasertib',
  'Caplacizumab',
  'Capsaicin',
  'Captopril',
  'Carbamazepine',
  'Carbetocin',
  'Carbimazole',
  'Carbocisteine',
  'Carbomers',
  'Carboplatin',
  'Carboprost',
  'Carfilzomib',
  'Carglumic acid',
  'Cariprazine',
  'Carmellose sodium',
  'Carmustine',
  'Carvedilol',
  'Caspofungin',
  'Castor oil with collodion and colophony',
  'Cefaclor',
  'Cefadroxil',
  'Cefalexin',
  'Cefazolin',
  'Cefepime',
  'Cefepime with enmetazobactam',
  'Cefiderocol',
  'Cefixime',
  'Cefotaxime',
  'Cefoxitin',
  'Cefradine',
  'Ceftaroline fosamil',
  'Ceftazidime',
  'Ceftazidime with avibactam',
  'Ceftobiprole',
  'Ceftolozane with tazobactam',
  'Ceftriaxone',
  'Cefuroxime',
  'Celecoxib',
  'Celiprolol hydrochloride',
  'Cemiplimab',
  'Cenobamate',
  'Ceritinib',
  'Certolizumab pegol',
  'Cetirizine hydrochloride',
  'Cetrimide with undecenoic acid',
  'Cetrorelix',
  'Cetuximab',
  'Chenodeoxycholic acid',
  'Chikungunya vaccine (live)',
  'Chloral hydrate',
  'Chlorambucil',
  'Chloramphenicol',
  'Chlordiazepoxide hydrochloride',
  'Chlorhexidine',
  'Chlorhexidine gluconate with isopropyl alcohol',
  'Chlorhexidine with cetrimide',
  'Chlorhexidine with lidocaine',
  'Chlorhexidine with neomycin',
  'Chlorhexidine with nystatin',
  'Chlormethine',
  'Chloroprocaine hydrochloride',
  'Chloroquine',
  'Chlorphenamine maleate',
  'Chlorpromazine hydrochloride',
  'Chlortalidone',
  'Cholera vaccine (inactivated)',
  'Cholera vaccine (live)',
  'Cholic acid',
  'Choline salicylate',
  'Choriogonadotropin alfa',
  'Ciclesonide',
  'Ciclosporin',
  'Cidofovir',
  'Cilostazol',
  'Cimetidine',
  'Cinacalcet',
  'Cinchocaine with hydrocortisone',
  'Cinchocaine with prednisolone',
  'Cinnarizine',
  'Cinnarizine with dimenhydrinate',
  'Cipaglucosidase alfa',
  'Ciprofibrate',
  'Ciprofloxacin',
  'Ciprofloxacin with dexamethasone',
  'Ciprofloxacin with fluocinolone acetonide',
  'Cisatracurium',
  'Cisplatin',
  'Citalopram',
  'Citric acid',
  'Citric acid with magnesium carbonate',
  'Citric acid with potassium citrate',
  'Cladribine',
  'Clarithromycin',
  'Clascoterone',
  'Clindamycin',
  'Clobazam',
  'Clobetasol propionate',
  'Clobetasol propionate with neomycin sulfate and nystatin',
  'Clobetasone butyrate',
  'Clobetasone butyrate with nystatin and oxytetracycline',
  'Clofarabine',
  'Clofazimine',
  'Clomethiazole',
  'Clomifene citrate',
  'Clomipramine hydrochloride',
  'Clonazepam',
  'Clonidine hydrochloride',
  'Clopidogrel',
  'Clotrimazole',
  'Clozapine',
  'Co-amilofruse',
  'Co-amilozide',
  'Co-amoxiclav',
  'Co-beneldopa',
  'Co-careldopa',
  'Co-codamol',
  'Co-cyprindiol',
  'Co-danthramer',
  'Co-danthrusate',
  'Co-fluampicil',
  'Co-magaldrox',
  'Co-phenotrope',
  'Co-tenidone',
  'Co-trimoxazole',
  'Coal tar',
  'Coal tar with calamine',
  'Coal tar with coconut oil and salicylic acid',
  'Coal tar with dithranol and salicylic acid',
  'Coal tar with salicylic acid',
  'Coal tar with salicylic acid and precipitated sulfur',
  'Coal tar with zinc oxide',
  'Cobicistat',
  'Cobimetinib',
  'Codeine phosphate',
  'Colchicine',
  'Colecalciferol',
  'Colecalciferol with calcium carbonate',
  'Colesevelam hydrochloride',
  'Colestipol hydrochloride',
  'Colestyramine',
  'Colistimethate sodium',
  'Conestat alfa',
  'Conjugated oestrogens',
  'Conjugated oestrogens with medroxyprogesterone',
  'COVID-19 vaccine',
  'Cranberry',
  'Crisantaspase',
  'Crizotinib',
  'Crotamiton',
  'Crovalimab',
  'Cyanocobalamin',
  'Cyclizine',
  'Cyclopentolate hydrochloride',
  'Cyclophosphamide',
  'Cycloserine',
  'Cyproheptadine hydrochloride',
  'Cyproterone acetate',
  'Cytarabine',
  'Cytisinicline',
  'Cytomegalovirus immunoglobulin',
  'Dabigatran etexilate',
  'Dabrafenib',
  'Dacarbazine',
  'Dacomitinib',
  'Dairy products',
  'Dalbavancin',
  'Dalteparin sodium',
  'Danaparoid sodium',
  'Danicopan',
  'Dantrolene sodium',
  'Dapagliflozin',
  'Dapagliflozin with metformin',
  'Dapoxetine',
  'Dapsone',
  'Daptomycin',
  'Daratumumab',
  'Darbepoetin alfa',
  'Daridorexant',
  'Darifenacin',
  'Darolutamide',
  'Darunavir',
  'Darunavir with cobicistat',
  'Darunavir with cobicistat, emtricitabine and tenofovir alafenamide',
  'Dasatinib',
  'Daunorubicin',
  'Daunorubicin with cytarabine',
  'Decitabine',
  'Decitabine with cedazuridine',
  'Deferasirox',
  'Deferiprone',
  'Deflazacort',
  'Degarelix',
  'Delafloxacin',
  'Delamanid',
  'Delgocitinib',
  'Demeclocycline hydrochloride',
  'Dengue vaccine',
  'Denosumab',
  'Dequalinium chloride',
  'Desferrioxamine mesilate',
  'Desflurane',
  'Desloratadine',
  'Desmopressin',
  'Desogestrel',
  'Deucravacitinib',
  'Deutivacaftor with tezacaftor and vanzacaftor',
  'Dexamethasone',
  'Dexamethasone with framycetin sulfate and gramicidin',
  'Dexamethasone with glacial acetic acid and neomycin sulfate',
  'Dexamethasone with hypromellose, neomycin and polymyxin B sulfate',
  'Dexamethasone with levofloxacin',
  'Dexamethasone with netilmicin',
  'Dexamethasone with tobramycin',
  'Dexamfetamine sulfate',
  'Dexketoprofen',
  'Dexmedetomidine',
  'Dexrazoxane',
  'Diamorphine hydrochloride',
  'Diazepam',
  'Diazoxide',
  'Diclofenac',
  'Diclofenac potassium',
  'Diclofenac sodium',
  'Diclofenac sodium with misoprostol',
  'Dicobalt edetate',
  'Dicycloverine hydrochloride',
  'Dicycloverine hydrochloride with aluminium hydroxide, magnesium oxide and simeticone',
  'Dienogest',
  'Dienogest with estradiol valerate',
  'Diethyl phthalate with methyl salicylate',
  'Diethylcarbamazine',
  'Diethylstilbestrol',
  'Difelikefalin',
  'Digoxin',
  'Digoxin-specific antibody fragments',
  'Dihydrocodeine tartrate',
  'Dihydrocodeine with paracetamol',
  'Diltiazem hydrochloride',
  'Dimethyl fumarate',
  'Dimeticone',
  'Dinoprostone',
  'Dinutuximab beta',
  'Diphtheria antitoxin',
  'Diphtheria with tetanus and pertussis vaccine',
  'Diphtheria with tetanus and poliomyelitis vaccine',
  'Diphtheria with tetanus, pertussis and poliomyelitis vaccine',
  'Diphtheria with tetanus, pertussis, hepatitis B, poliomyelitis and haemophilus influenzae type b vaccine',
  'Diphtheria with tetanus, pertussis, poliomyelitis and haemophilus influenzae type b vaccine',
  'Dipipanone hydrochloride with cyclizine',
  'Dipyridamole',
  'Diroximel fumarate',
  'Disodium hydrogen citrate with glucose, potassium chloride and sodium chloride',
  'Disopyramide',
  'Disulfiram',
  'Dithranol',
  'Dithranol with salicylic acid and zinc oxide',
  'Dobutamine',
  'Docetaxel',
  'Docusate sodium',
  'Dolutegravir',
  'Dolutegravir with rilpivirine',
  'Domperidone',
  'Donanemab',
  'Donepezil hydrochloride',
  'Dopamine hydrochloride',
  'Doravirine',
  'Dornase alfa',
  'Dorzolamide',
  'Dorzolamide with timolol',
  'Dostarlimab',
  'Dosulepin hydrochloride',
  'Doxapram hydrochloride',
  'Doxazosin',
  'Doxepin',
  'Doxorubicin hydrochloride',
  'Doxycycline',
  'Doxylamine with pyridoxine',
  'Dried prothrombin complex',
  'Dronedarone',
  'Droperidol',
  'Drospirenone',
  'Drospirenone with estetrol',
  'Dulaglutide',
  'Duloxetine',
  'Dupilumab',
  'Durvalumab',
  'Dutasteride',
  'Econazole nitrate',
  'Eculizumab',
  'Edoxaban',
  'Efavirenz',
  'Efavirenz with emtricitabine and tenofovir disoproxil',
  'Efgartigimod alfa',
  'Eflornithine',
  'Elacestrant',
  'Elafibranor',
  'Elbasvir with grazoprevir',
  'Eletriptan',
  'Eliglustat',
  'Elosulfase alfa',
  'Elotuzumab',
  'Elranatamab',
  'Eltrombopag',
  'Elvitegravir',
  'Elvitegravir with cobicistat, emtricitabine and tenofovir alafenamide',
  'Elvitegravir with cobicistat, emtricitabine and tenofovir disoproxil',
  'Emicizumab',
  'Emollient bath and shower products, antimicrobial-containing',
  'Emollient bath and shower products, paraffin-containing',
  'Emollient bath and shower products, soya-bean oil-containing',
  'Emollient creams and ointments, antimicrobial-containing',
  'Emollient creams and ointments, colloidal oatmeal-containing',
  'Emollient creams and ointments, hydrogenated castor oil-containing',
  'Emollient creams and ointments, paraffin-containing',
  'Emollients, urea-containing',
  'Empagliflozin',
  'Empagliflozin with linagliptin',
  'Empagliflozin with metformin',
  'Emtricitabine',
  'Emtricitabine with rilpivirine and tenofovir alafenamide',
  'Emtricitabine with rilpivirine and tenofovir disoproxil',
  'Emtricitabine with tenofovir alafenamide',
  'Emtricitabine with tenofovir disoproxil',
  'Enalapril maleate',
  'Enalapril with hydrochlorothiazide',
  'Encorafenib',
  'Enfortumab vedotin',
  'Enfuvirtide',
  'Enoxaparin sodium',
  'Enoximone',
  'Entacapone',
  'Entecavir',
  'Enteral feeds',
  'Entrectinib',
  'Enzalutamide',
  'Epcoritamab',
  'Ephedrine hydrochloride',
  'Epinastine hydrochloride',
  'Epirubicin hydrochloride',
  'Eplerenone',
  'Eplontersen',
  'Epoetin alfa',
  'Epoetin beta',
  'Epoetin zeta',
  'Epoprostenol',
  'Eprosartan',
  'Eptifibatide',
  'Eptinezumab',
  'Eravacycline',
  'Erdafitinib',
  'Erdosteine',
  'Erenumab',
  'Ergocalciferol',
  'Ergocalciferol with calcium lactate and calcium phosphate',
  'Ergometrine maleate',
  'Ergometrine with oxytocin',
  'Eribulin',
  'Erlotinib',
  'Ertapenem',
  'Ertugliflozin',
  'Erythromycin',
  'Erythromycin with zinc acetate',
  'Escitalopram',
  'Esketamine',
  'Eslicarbazepine acetate',
  'Esmolol hydrochloride',
  'Esomeprazole',
  'Estradiol',
  'Estradiol with dydrogesterone',
  'Estradiol with levonorgestrel',
  'Estradiol with medroxyprogesterone',
  'Estradiol with nomegestrol',
  'Estradiol with norethisterone',
  'Estradiol with progesterone',
  'Estramustine phosphate',
  'Estriol',
  'Eszopiclone',
  'Etanercept',
  'Etelcalcetide',
  'Ethambutol hydrochloride',
  'Ethinylestradiol',
  'Ethinylestradiol with desogestrel',
  'Ethinylestradiol with drospirenone',
  'Ethinylestradiol with etonogestrel',
  'Ethinylestradiol with gestodene',
  'Ethinylestradiol with levonorgestrel',
  'Ethinylestradiol with norelgestromin',
  'Ethinylestradiol with norethisterone',
  'Ethinylestradiol with norgestimate',
  'Ethosuximide',
  'Etodolac',
  'Etomidate',
  'Etonogestrel',
  'Etoposide',
  'Etoricoxib',
  'Etrasimod',
  'Etravirine',
  'Eucalyptus with menthol',
  'European viper snake venom antiserum',
  'Everolimus',
  'Evinacumab',
  'Evolocumab',
  'Exemestane',
  'Exenatide',
  'Ezetimibe',
  'Factor IX',
  'Factor VIIa (recombinant)',
  'Factor VIII',
  'Factor VIII inhibitor bypassing fraction',
  'Factor XIII',
  'Factor XIII A-subunit (recombinant)',
  'Famciclovir',
  'Famotidine',
  'Fampridine',
  'Faricimab',
  'Febuxostat',
  'Fedratinib',
  'Felbinac',
  'Felodipine',
  'Fenfluramine',
  'Fenofibrate',
  'Fentanyl',
  'Ferric carboxymaltose',
  'Ferric derisomaltose',
  'Ferric maltol',
  'Ferrous fumarate',
  'Ferrous fumarate with folic acid',
  'Ferrous gluconate',
  'Ferrous sulfate',
  'Ferrous sulfate with ascorbic acid',
  'Ferrous sulfate with folic acid',
  'Fesoterodine fumarate',
  'Fexofenadine hydrochloride',
  'Fezolinetant',
  'Fibrinogen, dried',
  'Fidaxomicin',
  'Filgotinib',
  'Filgrastim',
  'Finasteride',
  'Finerenone',
  'Fingolimod',
  'Flavoxate hydrochloride',
  'Flecainide acetate',
  'Flucloxacillin',
  'Fluconazole',
  'Flucytosine',
  'Fludarabine phosphate',
  'Fludrocortisone acetate',
  'Fludroxycortide',
  'Flumazenil',
  'Flumetasone pivalate with clioquinol',
  'Fluocinolone acetonide',
  'Fluocinonide',
  'Fluorescein sodium',
  'Fluorescein with lidocaine',
  'Fluorometholone',
  'Fluorouracil',
  'Fluorouracil with salicylic acid',
  'Fluoxetine',
  'Flupentixol',
  'Flupentixol decanoate',
  'Flurazepam',
  'Flurbiprofen',
  'Flutamide',
  'Fluticasone',
  'Fluticasone with azelastine',
  'Fluticasone with formoterol',
  'Fluticasone with salmeterol',
  'Fluticasone with umeclidinium and vilanterol',
  'Fluticasone with vilanterol',
  'Fluvastatin',
  'Fluvoxamine maleate',
  'Folic acid',
  'Folinic acid',
  'Follitropin alfa',
  'Follitropin alfa with lutropin alfa',
  'Follitropin delta',
  'Fondaparinux sodium',
  'Formaldehyde',
  'Formoterol fumarate',
  'Formoterol fumarate with glycopyrronium and budesonide',
  'Fosamprenavir',
  'Fosaprepitant',
  'Foscarnet sodium',
  'Fosfomycin',
  'Fosinopril sodium',
  'Foslevodopa with foscarbidopa',
  'Fosphenytoin sodium',
  'Fostamatinib',
  'Fostemsavir',
  'Framycetin sulfate',
  'Fremanezumab',
  'Fresh frozen plasma',
  'Frovatriptan',
  'Fruquintinib',
  'Fulvestrant',
  'Furosemide',
  'Furosemide with triamterene',
  'Fusidic acid',
  'Futibatinib',
  'Gabapentin',
  'Galantamine',
  'Galcanezumab',
  'Galsulfase',
  'Ganciclovir',
  'Ganirelix',
  'Garadacimab',
  'Gefitinib',
  'Gelatin',
  'Gemcitabine',
  'Gemeprost',
  'Gemfibrozil',
  'Gemtuzumab ozogamicin',
  'Gentamicin',
  'Gentamicin with hydrocortisone',
  'Gilteritinib',
  'Givinostat',
  'Givosiran',
  'Glasdegib',
  'Glatiramer acetate',
  'Glecaprevir with pibrentasvir',
  'Gliclazide',
  'Glimepiride',
  'Glipizide',
  'Glofitamab',
  'Glucagon',
  'Glucarpidase',
  'Glucosamine',
  'Glucose',
  'Glycerol',
  'Glycerol phenylbutyrate',
  'Glycerol with magnesium sulfate and phenol',
  'Glyceryl trinitrate',
  'Glycine',
  'Glycopyrronium bromide',
  'Glycopyrronium with formoterol fumarate',
  'Glycopyrronium with indacaterol',
  'Golimumab',
  'Gonadorelin',
  'Goserelin',
  'Granisetron',
  'Grapefruit',
  'Grass pollen extract',
  'Griseofulvin',
  'Guanfacine',
  'Guselkumab',
  'Haem arginate',
  'Haemophilus influenzae type b with meningococcal group C vaccine',
  'Haloperidol',
  'Haloperidol decanoate',
  'Heparin (unfractionated)',
  'Heparinoid',
  'Hepatitis A and B vaccine',
  'Hepatitis A vaccine',
  'Hepatitis B immunoglobulin',
  'Hepatitis B vaccine',
  'Herpes-zoster vaccine (recombinant, adjuvanted)',
  'Hexetidine',
  'Homatropine hydrobromide',
  'House dust mite extract',
  'Human alpha1-proteinase inhibitor',
  'Human papillomavirus vaccine',
  'Hyaluronidase',
  'Hydralazine hydrochloride',
  'Hydrochlorothiazide',
  'Hydrocortisone',
  'Hydrocortisone butyrate',
  'Hydrocortisone with benzalkonium chloride, dimeticone and nystatin',
  'Hydrocortisone with chlorhexidine hydrochloride and nystatin',
  'Hydrocortisone with clotrimazole',
  'Hydrocortisone with fusidic acid',
  'Hydrocortisone with lidocaine',
  'Hydrocortisone with miconazole',
  'Hydrocortisone with neomycin and polymyxin B sulfate',
  'Hydrocortisone with oxytetracycline',
  'Hydrogen peroxide',
  'Hydromorphone hydrochloride',
  'Hydroxocobalamin',
  'Hydroxycarbamide',
  'Hydroxychloroquine sulfate',
  'Hydroxyethylcellulose',
  'Hydroxypropyl guar with polyethylene glycol and propylene glycol',
  'Hydroxyzine hydrochloride',
  'Hyoscine butylbromide',
  'Hyoscine hydrobromide',
  'Hypromellose',
  'Hypromellose with dextran 70',
  'Ibandronic acid',
  'Ibrutinib',
  'Ibuprofen',
  'Icatibant',
  'Ichthammol',
  'Ichthammol with zinc oxide',
  'Icosapent ethyl',
  'Idarubicin hydrochloride',
  'Idarucizumab',
  'Idebenone',
  'Idelalisib',
  'Idursulfase',
  'Ifosfamide',
  'Iloprost',
  'Imatinib',
  'Imidapril hydrochloride',
  'Imiglucerase',
  'Imipenem with cilastatin',
  'Imipenem with cilastatin and relebactam',
  'Imipramine hydrochloride',
  'Imiquimod',
  'Inclisiran',
  'Indacaterol',
  'Indapamide',
  'Indometacin',
  'Indoramin',
  'Infliximab',
  'Influenza vaccine (inactivated)',
  'Influenza vaccine (live)',
  'Ingenol mebutate',
  'Inosine pranobex',
  'Inositol nicotinate',
  'Inotersen',
  'Inotuzumab ozogamicin',
  'Insulin',
  'Insulin aspart',
  'Insulin degludec',
  'Insulin degludec with liraglutide',
  'Insulin detemir',
  'Insulin glargine',
  'Insulin glargine with lixisenatide',
  'Insulin glulisine',
  'Insulin lispro',
  'Interferon beta',
  'Interferon gamma-1b',
  'Intra-uterine contraceptive devices (copper)',
  'Iodide with iodine',
  'Ipilimumab',
  'Ipratropium bromide',
  'Ipratropium with salbutamol',
  'Iptacopan',
  'Irbesartan',
  'Irbesartan with hydrochlorothiazide',
  'Irinotecan hydrochloride',
  'Iron dextran',
  'Iron sucrose',
  'Isatuximab',
  'Isavuconazole',
  'Isocarboxazid',
  'Isoflurane',
  'Isoniazid',
  'Isophane insulin',
  'Isoprenaline hydrochloride',
  'Isosorbide dinitrate',
  'Isosorbide mononitrate',
  'Isotretinoin',
  'Ispaghula husk',
  'Itraconazole',
  'Ivabradine',
  'Ivacaftor',
  'Ivacaftor with tezacaftor and elexacaftor',
  'Ivermectin',
  'Ivosidenib',
  'Ixazomib',
  'Ixekizumab',
  'Japanese encephalitis vaccine',
  'Kaolin with morphine',
  'Ketamine',
  'Ketoconazole',
  'Ketoprofen',
  'Ketorolac trometamol',
  'Ketotifen',
  'Labetalol hydrochloride',
  'Lacidipine',
  'Lacosamide',
  'Lactic acid',
  'Lactulose',
  'Lamivudine',
  'Lamivudine with dolutegravir',
  'Lamivudine with tenofovir disoproxil and doravirine',
  'Lamotrigine',
  'Lanadelumab',
  'Landiolol hydrochloride',
  'Lanreotide',
  'Lansoprazole',
  'Lanthanum',
  'Lapatinib',
  'Laronidase',
  'Larotrectinib',
  'Latanoprost',
  'Latanoprost with netarsudil',
  'Latanoprost with timolol',
  'Lauromacrogol 400',
  'Lazertinib',
  'Lebrikizumab',
  'Lecanemab',
  'Ledipasvir with sofosbuvir',
  'Leflunomide',
  'Lenacapavir',
  'Lenalidomide',
  'Leniolisib',
  'Lenograstim',
  'Lenvatinib',
  'Lercanidipine hydrochloride',
  'Letermovir',
  'Letrozole',
  'Leuprorelin acetate',
  'Levamisole',
  'Levetiracetam',
  'Levobunolol hydrochloride',
  'Levobupivacaine',
  'Levocarnitine',
  'Levocetirizine hydrochloride',
  'Levodopa with carbidopa and entacapone',
  'Levofloxacin',
  'Levofolinic acid',
  'Levomenthol',
  'Levomepromazine',
  'Levonorgestrel',
  'Levothyroxine sodium',
  'Lidocaine hydrochloride',
  'Lidocaine with adrenaline',
  'Lidocaine with cetrimide',
  'Lidocaine with phenylephrine',
  'Lidocaine with prilocaine',
  'Linaclotide',
  'Linagliptin',
  'Linagliptin with metformin',
  'Linezolid',
  'Linzagolix',
  'Liothyronine sodium',
  'Lipegfilgrastim',
  'Liquid paraffin',
  'Liquid paraffin with white soft paraffin and wool alcohols',
  'Liraglutide',
  'Lisdexamfetamine mesilate',
  'Lisinopril',
  'Lisinopril with hydrochlorothiazide',
  'Lithium carbonate',
  'Lithium citrate',
  'Lixisenatide',
  'Lodoxamide',
  'Lofepramine',
  'Lofexidine hydrochloride',
  'Lomitapide',
  'Lomustine',
  'Loncastuximab tesirine',
  'Loperamide hydrochloride',
  'Loperamide with simeticone',
  'Lopinavir with ritonavir',
  'Loprazolam',
  'Loratadine',
  'Lorazepam',
  'Lorlatinib',
  'Lormetazepam',
  'Losartan potassium',
  'Losartan with hydrochlorothiazide',
  'Loteprednol etabonate',
  'Loxapine',
  'Lumacaftor with ivacaftor',
  'Lumasiran',
  'Lurasidone hydrochloride',
  'Lusutrombopag',
  'Lutropin alfa',
  'Lymecycline',
  'Macitentan',
  'Macrogol 3350',
  'Macrogol 3350 with anhydrous sodium sulfate, ascorbic acid, potassium chloride, sodium ascorbate and sodium chloride',
  'Macrogol 3350 with anhydrous sodium sulfate, potassium chloride, sodium bicarbonate and sodium chloride',
  'Macrogol 3350 with potassium chloride, sodium bicarbonate and sodium chloride',
  'Magnesium aspartate',
  'Magnesium carbonate',
  'Magnesium citrate',
  'Magnesium citrate with sodium picosulfate',
  'Magnesium glycerophosphate',
  'Magnesium hydroxide',
  'Magnesium sulfate',
  'Magnesium trisilicate',
  'Magnesium trisilicate with magnesium carbonate and sodium bicarbonate',
  'Malathion',
  'Mannitol',
  'Maralixibat',
  'Maraviroc',
  'Maribavir',
  'Marstacimab',
  'Mavacamten',
  'Measles, mumps and rubella vaccine',
  'Mebendazole',
  'Mebeverine hydrochloride',
  'Mebeverine with ispaghula husk',
  'Medroxyprogesterone acetate',
  'Mefenamic acid',
  'Mefloquine',
  'Megestrol acetate',
  'Melatonin',
  'Meloxicam',
  'Melphalan',
  'Memantine hydrochloride',
  'Menadiol sodium phosphate',
  'Meningococcal group B vaccine (rDNA, component, adsorbed)',
  'Meningococcal groups A with C and W135 and Y vaccine',
  'Menotrophin',
  'Mepacrine hydrochloride',
  'Mepivacaine hydrochloride',
  'Mepivacaine with adrenaline',
  'Mepolizumab',
  'Meptazinol',
  'Mercaptamine',
  'Mercaptopurine',
  'Meropenem',
  'Meropenem with vaborbactam',
  'Mesalazine',
  'Mesna',
  'Metaraminol',
  'Metformin hydrochloride',
  'Methadone hydrochloride',
  'Methenamine hippurate',
  'Methocarbamol',
  'Methotrexate',
  'Methoxy polyethylene glycol-epoetin beta',
  'Methoxyflurane',
  'Methyldopa',
  'Methylnaltrexone bromide',
  'Methylphenidate hydrochloride',
  'Methylprednisolone',
  'Methylprednisolone with lidocaine',
  'Methylthioninium chloride',
  'Metoclopramide hydrochloride',
  'Metolazone',
  'Metoprolol tartrate',
  'Metreleptin',
  'Metronidazole',
  'Metyrapone',
  'Mexiletine',
  'Mianserin hydrochloride',
  'Micafungin',
  'Miconazole',
  'Midazolam',
  'Midodrine hydrochloride',
  'Midostaurin',
  'Mifamurtide',
  'Mifepristone',
  'Mifepristone and misoprostol',
  'Migalastat',
  'Miglustat',
  'Milrinone',
  'Minocycline',
  'Minoxidil',
  'Mirabegron',
  'Mirikizumab',
  'Mirtazapine',
  'Misoprostol',
  'Mitomycin',
  'Mitotane',
  'Mitoxantrone',
  'Mivacurium',
  'Mizolastine',
  'Mobocertinib',
  'Moclobemide',
  'Modafinil',
  'Mogamulizumab',
  'Molnupiravir',
  'Momelotinib',
  'Mometasone furoate',
  'Mometasone furoate with glycopyrronium bromide and indacaterol',
  'Mometasone furoate with olopatadine',
  'Montelukast',
  'Morphine',
  'Mosunetuzumab',
  'Moxifloxacin',
  'Moxonidine',
  'Mupirocin',
  'Mycophenolate mofetil',
  'Nabilone',
  'Nabumetone',
  'Nadolol',
  'Nafarelin',
  'Naftidrofuryl oxalate',
  'Naldemedine',
  'Nalmefene',
  'Naloxegol',
  'Naloxone hydrochloride',
  'Naltrexone hydrochloride',
  'Naltrexone with bupropion',
  'Naproxen',
  'Naproxen with esomeprazole',
  'Naratriptan',
  'Natalizumab',
  'Nebivolol',
  'Nefopam hydrochloride',
  'Nelarabine',
  'Nemolizumab',
  'Neomycin sulfate',
  'Neostigmine',
  'Neostigmine with glycopyrronium bromide',
  'Nepafenac',
  'Neratinib',
  'Netilmicin',
  'Nevirapine',
  'Nicardipine hydrochloride',
  'Nicorandil',
  'Nicotinamide',
  'Nicotine',
  'Nicotinic acid',
  'Nifedipine',
  'Nilotinib',
  'Nimodipine',
  'Nintedanib',
  'Niraparib',
  'Nirmatrelvir with ritonavir',
  'Nitisinone',
  'Nitrazepam',
  'Nitrofurantoin',
  'Nitrous oxide',
  'Nivolumab',
  'Nivolumab with relatlimab',
  'Nizatidine',
  'Nonoxinol',
  'Noradrenaline/norepinephrine',
  'Norethisterone',
  'Norethisterone with mestranol',
  'Normal immunoglobulin',
  'Nortriptyline',
  'Nusinersen',
  'Nystatin',
  'Obeticholic acid',
  'Obinutuzumab',
  'Ocrelizumab',
  'Ocriplasmin',
  'Octreotide',
  'Odevixibat',
  'Ofatumumab',
  'Ofloxacin',
  'Olanzapine',
  'Olanzapine embonate',
  'Olaparib',
  'Olipudase alfa',
  'Olive oil',
  'Olmesartan medoxomil',
  'Olmesartan with amlodipine',
  'Olmesartan with amlodipine and hydrochlorothiazide',
  'Olmesartan with hydrochlorothiazide',
  'Olodaterol',
  'Olopatadine',
  'Olsalazine sodium',
  'Omalizumab',
  'Omega-3-acid ethyl esters',
  'Omeprazole',
  'Ondansetron',
  'Opicapone',
  'Opium',
  'Oritavancin',
  'Orlistat',
  'Orphenadrine hydrochloride',
  'Oseltamivir',
  'Osilodrostat',
  'Osimertinib',
  'Ospemifene',
  'Oxaliplatin',
  'Oxazepam',
  'Oxcarbazepine',
  'Oxerutins',
  'Oxybuprocaine hydrochloride',
  'Oxybutynin hydrochloride',
  'Oxycodone hydrochloride',
  'Oxycodone with naloxone',
  'Oxymetholone',
  'Oxytetracycline',
  'Oxytocin',
  'Ozanimod',
  'Paclitaxel',
  'Palbociclib',
  'Paliperidone',
  'Palonosetron',
  'Palonosetron with netupitant',
  'Palopegteriparatide',
  'Pamidronate disodium',
  'Pancreatin',
  'Pancuronium bromide',
  'Panitumumab',
  'Panobinostat',
  'Pantoprazole',
  'Paracetamol',
  'Paracetamol with buclizine hydrochloride and codeine phosphate',
  'Paracetamol with isometheptene',
  'Paraffin, yellow, soft',
  'Parathyroid hormone',
  'Parecoxib',
  'Parenteral nutrition supplements',
  'Paricalcitol',
  'Paroxetine',
  'Pasireotide',
  'Patiromer calcium',
  'Patisiran',
  'Pazopanib',
  'Peanut protein',
  'Pegaspargase',
  'Pegcetacoplan',
  'Pegfilgrastim',
  'Peginterferon alfa',
  'Peginterferon beta-1a',
  'Pegunigalsidase alfa',
  'Pegvisomant',
  'Pegzilarginase',
  'Pembrolizumab',
  'Pemetrexed',
  'Pemigatinib',
  'Penicillamine',
  'Pentamidine isetionate',
  'Pentazocine',
  'Pentosan polysulfate sodium',
  'Pentostatin',
  'Pentoxifylline',
  'Peppermint oil',
  'Perampanel',
  'Pericyazine',
  'Perindopril arginine',
  'Perindopril arginine with indapamide',
  'Perindopril erbumine',
  'Perindopril erbumine with amlodipine',
  'Permethrin',
  'Pertuzumab',
  'Pertuzumab with trastuzumab',
  'Pethidine hydrochloride',
  'Phenazone with lidocaine',
  'Phenelzine',
  'Phenindione',
  'Phenobarbital',
  'Phenol',
  'Phenoxybenzamine hydrochloride',
  'Phenoxymethylpenicillin',
  'Phenylephrine hydrochloride',
  'Phenylephrine with tropicamide',
  'Phenytoin',
  'Phosphate',
  'Phytomenadione',
  'Pilocarpine',
  'Pimecrolimus',
  'Pimozide',
  'Pindolol',
  'Pioglitazone',
  'Pioglitazone with metformin',
  'Piperacillin with tazobactam',
  'Piperaquine phosphate with artenimol',
  'Piracetam',
  'Pirfenidone',
  'Piroxicam',
  'Pitolisant',
  'Pivmecillinam hydrochloride',
  'Pixantrone',
  'Pizotifen',
  'Plerixafor',
  'Pneumococcal polysaccharide conjugate vaccine (adsorbed)',
  'Pneumococcal polysaccharide vaccine',
  'Podophyllotoxin',
  'Polatuzumab vedotin',
  'Polyvinyl alcohol',
  'Pomalidomide',
  'Ponatinib',
  'Ponesimod',
  'Posaconazole',
  'Potassium aminobenzoate',
  'Potassium bicarbonate with potassium acid tartrate',
  'Potassium chloride',
  'Potassium chloride with calcium chloride dihydrate and sodium chloride',
  'Potassium chloride with calcium chloride, sodium chloride and sodium lactate',
  'Potassium chloride with glucose',
  'Potassium chloride with glucose and sodium chloride',
  'Potassium chloride with potassium bicarbonate',
  'Potassium chloride with rice powder, sodium chloride and sodium citrate',
  'Potassium chloride with sodium chloride',
  'Potassium citrate with potassium bicarbonate',
  'Potassium permanganate',
  'Povidone-iodine',
  'Pralidoxime chloride',
  'Pralsetinib',
  'Pramipexole',
  'Prasterone',
  'Prasugrel',
  'Pravastatin sodium',
  'Praziquantel',
  'Prazosin',
  'Prednisolone',
  'Pregabalin',
  'Pridinol',
  'Prilocaine hydrochloride',
  'Prilocaine with felypressin',
  'Primaquine',
  'Primidone',
  'Procarbazine',
  'Prochlorperazine',
  'Procyclidine hydrochloride',
  'Progesterone',
  'Promazine hydrochloride',
  'Promethazine hydrochloride',
  'Promethazine teoclate',
  'Propafenone hydrochloride',
  'Propamidine isetionate',
  'Propantheline bromide',
  'Propiverine hydrochloride',
  'Propofol',
  'Propranolol hydrochloride',
  'Propylthiouracil',
  'Protamine sulfate',
  'Protein C concentrate',
  'Proxymetacaine hydrochloride',
  'Prucalopride',
  'Pseudoephedrine hydrochloride',
  'Pyrazinamide',
  'Pyridostigmine bromide',
  'Pyridoxine hydrochloride',
  'Pyrimethamine',
  'Quetiapine',
  'Quinagolide',
  'Quinapril',
  'Quinapril with hydrochlorothiazide',
  'Quinine',
  'Quizartinib',
  'Rabeprazole sodium',
  'Rabies immunoglobulin',
  'Rabies vaccine',
  'Raloxifene hydrochloride',
  'Raltegravir',
  'Raltitrexed',
  'Ramipril',
  'Ramipril with felodipine',
  'Ramucirumab',
  'Ranibizumab',
  'Ranitidine',
  'Ranolazine',
  'Rasagiline',
  'Rasburicase',
  'Ravulizumab',
  'Reboxetine',
  'Regorafenib',
  'Relugolix',
  'Relugolix with estradiol and norethisterone acetate',
  'Remdesivir',
  'Remifentanil',
  'Remimazolam',
  'Repaglinide',
  'Reslizumab',
  'Respiratory syncytial virus (RSV) vaccine',
  'Retinol palmitate with white soft paraffin, light liquid paraffin, liquid paraffin and wool fat',
  'Rezafungin',
  'Ribavirin',
  'Ribociclib',
  'Rifabutin',
  'Rifampicin',
  'Rifampicin with ethambutol, isoniazid and pyrazinamide',
  'Rifampicin with isoniazid',
  'Rifampicin with isoniazid and pyrazinamide',
  'Rifaximin',
  'Rilpivirine',
  'Riluzole',
  'Rimegepant',
  'Riociguat',
  'Ripretinib',
  'Risankizumab',
  'Risdiplam',
  'Risedronate sodium',
  'Risedronate with calcium carbonate and colecalciferol',
  'Risperidone',
  'Ritlecitinib',
  'Ritonavir',
  'Rituximab',
  'Rivaroxaban',
  'Rivastigmine',
  'Rizatriptan',
  'Rocuronium bromide',
  'Roflumilast',
  'Romiplostim',
  'Romosozumab',
  'Ropeginterferon alfa-2b',
  'Ropinirole',
  'Ropivacaine hydrochloride',
  'Rosuvastatin',
  'Rotavirus vaccine',
  'Rotigotine',
  'Roxadustat',
  'Rozanolixizumab',
  'Rucaparib',
  'Rufinamide',
  'Rupatadine',
  'Ruxolitinib',
  'Sacituzumab govitecan',
  'Sacubitril with valsartan',
  'Safinamide',
  'Salbutamol',
  'Salicylic acid',
  'Salicylic acid with lactic acid',
  'Salicylic acid with rhubarb extract',
  'Salicylic acid with zinc oxide',
  'Salmeterol',
  'Sapropterin dihydrochloride',
  'Sarilumab',
  'Satralizumab',
  'Saxagliptin',
  'Saxagliptin with dapagliflozin',
  'Saxagliptin with metformin',
  'Sebelipase alfa',
  'Secukinumab',
  'Seladelpar',
  'Selegiline hydrochloride',
  'Selenium',
  'Selexipag',
  'Selinexor',
  'Selpercatinib',
  'Semaglutide',
  'Senna',
  'Senna with ispaghula husk',
  'Sertraline',
  'Setmelanotide',
  'Sevelamer',
  'Sevoflurane',
  'Sildenafil',
  'Siltuximab',
  'Silver nitrate',
  'Silver sulfadiazine',
  'Simeticone',
  'Simeticone with aluminium hydroxide and magnesium hydroxide',
  'Simvastatin',
  'Simvastatin with ezetimibe',
  'Siponimod',
  'Sirolimus',
  'Sitagliptin',
  'Sitagliptin with metformin',
  'Sodium acid phosphate with sodium bicarbonate',
  'Sodium acid phosphate with sodium phosphate',
  'Sodium alginate with calcium carbonate and sodium bicarbonate',
  'Sodium alginate with potassium bicarbonate',
  'Sodium benzoate',
  'Sodium bicarbonate',
  'Sodium bicarbonate with sodium chloride',
  'Sodium chloride',
  'Sodium chloride with glucose',
  'Sodium citrate',
  'Sodium clodronate',
  'Sodium cromoglicate',
  'Sodium feredetate',
  'Sodium fluoride',
  'Sodium hyaluronate',
  'Sodium hyaluronate with trehalose',
  'Sodium nitrite',
  'Sodium nitroprusside',
  'Sodium oxybate',
  'Sodium phenylbutyrate',
  'Sodium picosulfate',
  'Sodium polystyrene sulfonate',
  'Sodium tetradecyl sulfate',
  'Sodium thiosulfate',
  'Sodium valproate',
  'Sodium zirconium cyclosilicate',
  'Sofosbuvir',
  'Sofosbuvir with velpatasvir',
  'Sofosbuvir with velpatasvir and voxilaprevir',
  'Solifenacin succinate',
  'Solriamfetol',
  'Somapacitan',
  'Somatropin',
  'Sorafenib',
  'Sotalol hydrochloride',
  'Sotatercept',
  'Sotorasib',
  'Sotrovimab',
  'Sparsentan',
  'Spesolimab',
  'Spironolactone',
  'Spironolactone with furosemide',
  'St John\'s wort',
  'Sterculia',
  'Sterculia with frangula',
  'Stiripentol',
  'Streptokinase',
  'Streptomycin',
  'Streptozocin',
  'Strontium ranelate',
  'Sucralfate',
  'Sucroferric oxyhydroxide',
  'Sufentanil',
  'Sugammadex',
  'Sulfadiazine',
  'Sulfasalazine',
  'Sulindac',
  'Sulpiride',
  'Sumatriptan',
  'Sumatriptan with naproxen',
  'Sunitinib',
  'Suxamethonium chloride',
  'Tacalcitol',
  'Tacrolimus',
  'Tadalafil',
  'Tafamidis',
  'Tafasitamab',
  'Tafluprost',
  'Tafluprost with timolol',
  'Talazoparib',
  'Talimogene laherparepvec',
  'Talquetamab',
  'Tamoxifen',
  'Tamsulosin hydrochloride',
  'Tamsulosin with dutasteride',
  'Tamsulosin with solifenacin',
  'Tapentadol',
  'Tarlatamab',
  'Tebentafusp',
  'Teclistamab',
  'Tedizolid',
  'Teduglutide',
  'Tegafur with gimeracil and oteracil',
  'Teicoplanin',
  'Telmisartan',
  'Telmisartan with hydrochlorothiazide',
  'Telotristat ethyl',
  'Temazepam',
  'Temocillin',
  'Temoporfin',
  'Temozolomide',
  'Temsirolimus',
  'Tenecteplase',
  'Tenofovir alafenamide',
  'Tenofovir disoproxil',
  'Tenoxicam',
  'Tepotinib',
  'Terazosin',
  'Terbinafine',
  'Terbutaline sulfate',
  'Teriflunomide',
  'Teriparatide',
  'Terlipressin acetate',
  'Testosterone',
  'Testosterone decanoate, isocaproate, phenylpropionate and propionate',
  'Testosterone enantate',
  'Testosterone propionate',
  'Testosterone undecanoate',
  'Tetanus immunoglobulin',
  'Tetrabenazine',
  'Tetracaine',
  'Tetracosactide',
  'Tetracycline',
  'Tezacaftor with ivacaftor',
  'Tezepelumab',
  'Thalidomide',
  'Theophylline',
  'Thiamine',
  'Thiopental sodium',
  'Thiotepa',
  'Thyrotropin alfa',
  'Tiagabine',
  'Tiaprofenic acid',
  'Tibolone',
  'Ticagrelor',
  'Tick-borne encephalitis vaccine',
  'Tigecycline',
  'Tildrakizumab',
  'Timolol maleate',
  'Timolol with bendroflumethiazide',
  'Tinzaparin sodium',
  'Tioconazole',
  'Tioguanine',
  'Tiotropium',
  'Tiotropium with olodaterol',
  'Tirbanibulin',
  'Tirofiban',
  'Tirzepatide',
  'Tivozanib',
  'Tizanidine',
  'Tobramycin',
  'Tocilizumab',
  'Tofacitinib',
  'Tolbutamide',
  'Tolcapone',
  'Tolfenamic acid',
  'Tolterodine tartrate',
  'Tolvaptan',
  'Topiramate',
  'Topotecan',
  'Torasemide',
  'Toremifene',
  'Trabectedin',
  'Tralokinumab',
  'Tramadol hydrochloride',
  'Tramadol with dexketoprofen',
  'Tramadol with paracetamol',
  'Trametinib',
  'Trandolapril',
  'Tranexamic acid',
  'Tranylcypromine',
  'Trastuzumab',
  'Trastuzumab deruxtecan',
  'Trastuzumab emtansine',
  'Travoprost',
  'Travoprost with timolol',
  'Trazodone hydrochloride',
  'Tree pollen extract',
  'Tremelimumab',
  'Treosulfan',
  'Treprostinil',
  'Tretinoin',
  'Tretinoin with clindamycin',
  'Tretinoin with erythromycin',
  'Triamcinolone acetonide',
  'Triamcinolone hexacetonide',
  'Triamterene',
  'Triamterene with chlortalidone',
  'Trientine',
  'Trifarotene',
  'Trifluoperazine',
  'Trifluridine with tipiracil',
  'Trihexyphenidyl hydrochloride',
  'Trimethoprim',
  'Trimipramine',
  'Triptorelin',
  'Tropicamide',
  'Tropicamide with phenylephrine and lidocaine',
  'Trospium chloride',
  'Tryptophan',
  'Tuberculin purified protein derivative',
  'Tucatinib',
  'Typhoid vaccine (inactivated)',
  'Typhoid vaccine (live)',
  'Ublituximab',
  'Ulipristal acetate',
  'Umeclidinium',
  'Umeclidinium with vilanterol',
  'Undecenoic acid with zinc undecenoate',
  'Upadacitinib',
  'Urea (13C)',
  'Urea hydrogen peroxide',
  'Urofollitropin',
  'Urokinase',
  'Ursodeoxycholic acid',
  'Ustekinumab',
  'Vadadustat',
  'Valaciclovir',
  'Valganciclovir',
  'Valproic acid',
  'Valsartan',
  'Valsartan with hydrochlorothiazide',
  'Vamorolone',
  'Vancomycin',
  'Vandetanib',
  'Vardenafil',
  'Varenicline',
  'Varicella-zoster immunoglobulin',
  'Varicella-zoster vaccine',
  'Vasopressin',
  'Vecuronium bromide',
  'Vedolizumab',
  'Velaglucerase alfa',
  'Velmanase alfa',
  'Vemurafenib',
  'Venetoclax',
  'Venlafaxine',
  'Verapamil hydrochloride',
  'Vericiguat',
  'Vernakalant',
  'Verteporfin',
  'Vestronidase alfa',
  'Vibegron',
  'Vigabatrin',
  'Vildagliptin',
  'Vildagliptin with metformin',
  'Vinblastine sulfate',
  'Vincristine sulfate',
  'Vindesine sulfate',
  'Vinorelbine',
  'Vismodegib',
  'Vitamin A',
  'Vitamin B complex',
  'Vitamin B substances with ascorbic acid',
  'Vitamins A and D',
  'Vitamins A, C and D',
  'Vitamins with minerals and trace elements',
  'Voclosporin',
  'Volanesorsen',
  'Von Willebrand factor',
  'Voriconazole',
  'Vortioxetine',
  'Vutrisiran',
  'Warfarin sodium',
  'Wasp venom extract',
  'Xipamide',
  'Xylometazoline hydrochloride',
  'Yellow fever vaccine',
  'Zanamivir',
  'Zanubrutinib',
  'Zidovudine',
  'Zidovudine with lamivudine',
  'Zilucoplan',
  'Zinc acetate',
  'Zinc sulfate',
  'Zolbetuximab',
  'Zoledronic acid',
  'Zolmitriptan',
  'Zolpidem tartrate',
  'Zonisamide',
  'Zopiclone',
  'Zuclopenthixol',
  'Zuclopenthixol acetate',
  'Zuclopenthixol decanoate',
];
