import * as firestore from 'firebase/firestore';
import type { EPRFForm, User as AppUser } from '../types';

export const getInitialFormState = (eventName: string | null, location: string | null, user: AppUser | null): EPRFForm => {
  const now = new Date();
  const timeString = now.toTimeString().split(' ')[0].substring(0, 5);
  const fullName = user ? `${user.firstName} ${user.lastName}`.trim() : '';
  return {
    patientId: null,
    // FIX: Initialize shiftId to correctly link to shifts.
    shiftId: null,
    eventName: eventName || null,
    presentationType: 'Medical/Trauma',
    natureOfCall: 'Emergency',
    incidentNumber: '',
    incidentDate: now.toISOString().split('T')[0],
    incidentTime: timeString,
    timeOfCall: timeString,
    onSceneTime: timeString,
    atPatientTime: '',
    leftSceneTime: '',
    atDestinationTime: '',
    clearDestinationTime: '',
    incidentLocation: location || '',
    patientName: '',
    patientAge: '',
    patientGender: 'Unknown',
    presentingComplaint: '',
    history: '',
    socialHistory: '',
    mechanismOfInjury: '',
    allergies: [],
    medications: [],
    pastMedicalHistory: '',
    lastOralIntake: '',
    painAssessment: { onset: '', provocation: '', quality: '', radiation: '', severity: 0, time: '' },
    airway: '',
    breathing: '',
    circulation: '',
    disability: { 
      avpu: 'Alert', 
      gcs: { eyes: 4, verbal: 5, motor: 6, total: 15 }, 
      pupils: { leftSize: '', leftResponse: 'Normal', rightSize: '', rightResponse: 'Normal' },
      bloodGlucoseLevel: '',
      fastTest: {
        face: 'Normal',
        arms: 'Normal',
        speech: 'Normal',
      },
    },
    exposure: '',
    airwayDetails: {
        status: 'Clear',
        adjuncts: [],
    },
    breathingDetails: {
        effort: 'Normal',
        sounds: ['Clear'],
        sides: ['Bilaterally'],
    },
    circulationDetails: {
        pulseQuality: 'Strong',
        skin: 'Normal',
        capillaryRefillTime: '',
        heartSounds: '',
    },
    limbAssessment: {
        luPower: '5',
        luSensation: 'Normal',
        llPower: '5',
        llSensation: 'Normal',
        ruPower: '5',
        ruSensation: 'Normal',
        rlPower: '5',
        rlSensation: 'Normal',
    },
    vitals: [{ time: timeString, hr: '', rr: '', bp: '', spo2: '', temp: '', bg: '', painScore: '0', avpu: 'Alert', onOxygen: false }],
    secondarySurvey: '',
    injuries: [],
    impressions: [],
    medicationsAdministered: [],
    interventions: [],
    itemsUsed: [],
    otherAgencies: [],
    disposition: 'Not Set',
    dispositionDetails: { destination: '', handoverTo: '', referralDetails: '' },
    handoverDetails: '',
    refusalOfCare: { refusedTreatment: false, refusedTransport: false, risksExplained: false, capacityDemonstrated: false, details: '' },
    safeguarding: { concerns: [], details: '' },
    mentalCapacity: { assessment: [], outcome: 'Not Assessed', details: '' },
    welfareLog: [],
    attachments: [],
    patientSignatureUrl: '',
    clinicianSignatureUrl: '',
    signaturesNeedSync: false,
    crewMembers: user ? [{ uid: user.uid, name: fullName }] : [],
    createdAt: firestore.Timestamp.now(),
    createdBy: user ? { uid: user.uid, name: fullName } : { uid: '', name: '' },
    status: 'Draft',
    auditLog: [],
    containsRestrictedDrugs: false,
  }
};